apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-newstructure-1-oct30
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/test-newstructure-1-oct30:15cd689a809302d9e321f31693f0b8a610c6c787@sha256:cf605bb4c702d62dc22015cb9d95950b7cebd612aaaf1e82b040d5d683e670dd # use pre-built to bootstrap 
          name: app-inference
