apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: test-newstructure-1-oct30-gitops-repository
spec:
  url: https://github.com/jdubrick-ai/test-newstructure-1-oct30-gitops